// Default constants

const
  DEFAULT_OBSERVER_CLEAR_INTERVAL = 300000,
  SERVER_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH:mm:ss';

module.exports = {
  DEFAULT_OBSERVER_CLEAR_INTERVAL,
  SERVER_TIMESTAMP_FORMAT
};